# Generated by Django 5.0.7 on 2024-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
