# Generated by Django 5.0.7 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="max_questions",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
