# Generated by Django 5.0.7 on 2024-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_subscription_max_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="max_quizes",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
