# Generated by Django 5.0.7 on 2024-08-11 11:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_subscriber_email_delete_osubscriber"),
        ("quiz", "0003_alter_quiz_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                default=17,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.subscriber",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 11, 16, 56, 51, 585666)
            ),
        ),
    ]
