# Generated by Django 5.0.7 on 2024-07-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSubscriber',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=101)),
                ('password', models.CharField(max_length=512)),
                ('mobile', models.IntegerField()),
                ('org', models.CharField(max_length=100)),
                ('active_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=101)),
                ('password', models.CharField(max_length=512)),
                ('mobile', models.IntegerField()),
                ('org', models.CharField(max_length=100)),
                ('active_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
    ]
