# Generated by Django 5.0.7 on 2024-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=101, unique=True),
        ),
        migrations.DeleteModel(
            name="OSubscriber",
        ),
    ]
